<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>df0c8896-0776-483b-a36b-1786d79a7a57</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EventBusRabbitMQ\EventBusRabbitMQ.csproj" />
    <ProjectReference Include="..\..\Huddle.ServiceDefaults\Huddle.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Huddle.Channel.Application\Huddle.Channel.Application.csproj" />
    <ProjectReference Include="..\Huddle.Channel.Infrastructure\Huddle.Channel.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\Shared\Protos\channel_access.proto" GrpcServices="Server" Link="Protos/%(Filename)%(Extension)"/>
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
  </ItemGroup>

</Project>
